
register_table = {
    '$zero': '0',
    '$at': '1',
    '$v0': '2',
    '$v1': '3',
    '$a0': '4',
    '$a1': '5',
    '$a2': '6',
    '$a3': '7',
    '$t0': '8',
    '$t1': '9',
    '$t2': 'A',    #10
    '$t3': 'B',    #11
    '$t4': 'C',
    '$t5': 'D',
    '$t6': 'E',
    '$t7': 'F',
    '$s0': '10',
    '$s1': '11',
    '$s2': '12',
    '$s3': '13',
    '$s4': '14',
    '$s5': '15',
    '$s6': '16',
    '$s7': '17',
    '$t8': '18',
    '$t9': '19',
    '$k0': '1A',
    '$k1': '1B',
    '$gp': '1C',
    '$sp': '1D',
    '$fp': '1E',
    '$ra': '1F'
}


instruction_table = {
    'add': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x20'},
    'and': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x24'},
    'nor': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x27'},
    'or': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x25'},
    'sub': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x22'},
    'sll': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x00'},
    'srl': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x02'},
    'slt': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x2A'},
    'beq': {'type': 'IFormat', 'opcode': '0x04'},
    'bne': {'type': 'IFormat', 'opcode': '0x05'},
    'lw': {'type': 'IFormat', 'opcode': '0x23'},
    'sw': {'type': 'IFormat', 'opcode': '0x2B'},
    'jr': {'type': 'RFormat', 'opcode': '0x00', 'func': '0x8'},
    'addi': {'type': 'IFormat', 'opcode': '0x08'},
    'ori': {'type': 'IFormat', 'opcode': '0x0D'},
    'andi': {'type': 'IFormat', 'opcode': '0x0C'},
    'j': {'type': 'JFormat', 'opcode': '0x02'},
    'jal': {'type': 'JFormat', 'opcode': '0x03'},
}
